sudo: false
language: python
python:
  - "2.7"
  - "pypy"
services:
  - "mysql"
  - "postgresql"
install:
  - "pip install pymysql"
  - "pip install psycopg2 mysql-python || true"
before_script:
  - cp test/travis.cfg test_drivers.cfg
  - mysql -e 'create database gauged;'
  - psql -c 'create database gauged;' -U postgres
script: make check
matrix:
  allow_failures:
    - "python": "pypy"
